CREATE SCHEMA IF NOT EXISTS delivery;

CREATE TABLE IF NOT EXISTS delivery.address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country    VARCHAR(50),
    city       VARCHAR(50),
    street     VARCHAR(100),
    house      VARCHAR(10),
    flat       VARCHAR(10)
    );

CREATE TABLE IF NOT EXISTS delivery.delivery (
    delivery_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_address_id   BIGINT REFERENCES delivery.address(address_id),
    to_address_id     BIGINT REFERENCES delivery.address(address_id),
    order_id          UUID UNIQUE,
    delivery_state    VARCHAR(15) NOT NULL,

    delivery_weight   DOUBLE PRECISION NOT NULL DEFAULT 0,
    delivery_volume   DOUBLE PRECISION NOT NULL DEFAULT 0,
    fragile           BOOLEAN NOT NULL DEFAULT FALSE
    );