spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=warehouse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql